const {test}=require('node:test');
const assert=require('node:assert/strict');
const {createHash}=require('node:crypto');
const {createServer}=require('../server.cjs');
const hash=x=>createHash('sha256').update(x).digest('hex');
async function fixture(t){const values=new Map(),media=new Map();const store={async get(k){return values.get(k)||null;},async put(k,text,etag){const old=values.get(k);if(etag!==(old?.etag||'null_etag'))throw {$metadata:{httpStatusCode:412}};values.set(k,{text,etag:'"'+hash(text)+'"'});},async exists(k){return media.has(k);},async upload(k,stream){const chunks=[];for await(const c of stream)chunks.push(c);media.set(k,Buffer.concat(chunks));},async url(k){return 'https://test.storageapi.dev/'+k;}};const server=createServer(store,{legacyFamilies:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});return {url:'http://127.0.0.1:'+server.address().port+'/api/families/'+'a'.repeat(64),server,values,media};}
const auth='Bearer '+'b'.repeat(64);
const data={version:1,revision:'first',iv:'a'.repeat(16),chunks:['c2VjcmV0']};
test('Family writes require a private capability and conditional revision',async t=>{const {url}=await fixture(t);assert.equal((await fetch(url)).status,401);assert.equal((await fetch(url,{method:'PUT',headers:{Authorization:auth},body:JSON.stringify(data)})).status,428);const put=await fetch(url,{method:'PUT',headers:{Authorization:auth,'If-Match':'null_etag'},body:JSON.stringify(data)});assert.equal(put.status,200);const read=await fetch(url,{headers:{Authorization:auth}});assert.deepEqual(await read.json(),data);assert.equal((await fetch(url,{method:'PUT',headers:{Authorization:auth,'If-Match':'null_etag'},body:JSON.stringify(data)})).status,412);assert.equal((await fetch(url,{method:'PUT',headers:{Authorization:auth,'If-Match':read.headers.get('etag')},body:JSON.stringify({...data,revision:'next'})})).status,200);});
test('A different capability cannot read or replace an existing family',async t=>{const {url}=await fixture(t);await fetch(url,{method:'PUT',headers:{Authorization:auth,'If-Match':'null_etag'},body:JSON.stringify(data)});assert.equal(await (await fetch(url,{headers:{Authorization:'Bearer '+'c'.repeat(64)}})).json(),null);assert.equal((await fetch(url,{headers:{Authorization:auth,Origin:'https://untrusted.example'}})).status,403);});
test('Uploads validate hashes and never expose server files',async t=>{const {url,media}=await fixture(t);const payload=Buffer.from('encrypted-test-file-bytes');let r=await fetch(url+'/media/'+hash(payload),{method:'PUT',headers:{Authorization:auth},body:payload});assert.equal(r.status,200);assert.equal(media.size,1);r=await fetch(url+'/media/'+'f'.repeat(64),{method:'PUT',headers:{Authorization:auth},body:payload});assert.equal(r.status,503);assert.equal(media.size,1);assert.equal((await fetch(new URL('/server.cjs',url))).status,404);assert.equal((await fetch(new URL('/.env',url))).status,404);});
test('Malformed encrypted snapshots are rejected without replacing data',async t=>{const {url}=await fixture(t);assert.equal((await fetch(url,{method:'PUT',headers:{Authorization:auth,'If-Match':'null_etag'},body:'{"version":1,"profiles":[]}'})).status,400);assert.equal(await(await fetch(url,{headers:{Authorization:auth}})).json(),null);});
